[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package="github.com/florimondmanca/go-live-chat"
  go-version="go1.10.1"
